# Generated by Django 2.1.2 on 2018-10-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='S',
        ),
    ]
